import React,{useEffect,useState} from 'react';import{createRoot}from'react-dom/client';import'./styles.css';
let tourVersion:number|undefined;
const api=async(path:string,opts?:RequestInit)=>{const base:Record<string,string>={'Content-Type':'application/json',...((opts?.headers as Record<string,string>)||{})};if(opts?.method&&opts.method!=='GET'&&tourVersion!==undefined&&!base['If-Match'])base['If-Match']=String(tourVersion);const r=await fetch('/api/v1'+path,{...opts,headers:base});const d=await r.json().catch(()=>({}));if(!r.ok){const e:any=Error(d.message||'请求失败');e.status=r.status;e.code=d.code;throw e}if(d.tour&&Number.isInteger(d.tour.version))tourVersion=d.tour.version;return d};
type Tour=any;
function App(){const[tour,setTour]=useState<Tour|null>(null);const[data,setData]=useState<any>();const[busy,setBusy]=useState(false);const[msg,setMsg]=useState('');const[perf,setPerf]=useState<any>();const[draft,setDraft]=useState<any>({playId:'moon',assignments:{},timeline:[],endings:[0,0,0]});
 useEffect(()=>{api('/tours').then(()=>{const id=localStorage.getItem('tour');if(id)api('/tours/'+id).then(x=>{setTour(x.tour);setData(x)}).catch(()=>{localStorage.removeItem('tour');setMsg('存档读取失败，请开始新的巡演。')})}).catch(()=>setMsg('无法连接巡演服务，请确认 API 已启动后重试。'))},[]);
 const act=async(fn:()=>Promise<any>)=>{setBusy(true);setMsg('');try{const d=await fn();if(d.tour){setTour(d.tour);setData(x=>({...x,...d}))}if(d.performance)setPerf(d.performance);if(d.ending)setMsg(`终局：${d.ending}（平均 ${d.average} 分）`)}catch(e:any){if(e.status===409&&tour){try{const x=await api('/tours/'+tour.id);setTour(x.tour);setData(x)}catch{}setMsg('存档已被其他操作更新，已同步最新进度，请重试。')}else setMsg(e.message)}finally{setBusy(false)}};
 const create=()=>act(async()=>{const created=await api('/tours',{method:'POST',body:JSON.stringify({name:'纸月剧团'})});localStorage.setItem('tour',created.tour.id);const d=await api('/tours/'+created.tour.id);setData(d);return d});
 useEffect(()=>{if(tour&&(tour.status==='PREPARING'||tour.status==='READY'))api('/tours/'+tour.id+'/production').then(d=>setDraft(d.draft))},[tour?.id,tour?.status]);
 if(!tour)return <main className="landing"><div className="curtain"><span>木偶剧团</span><h1>巡演</h1><p>把一段传说，交给下一座小镇。</p>{msg&&<div className="notice">{msg}</div>}<button onClick={create}>开始一场新的巡演</button></div></main>;
 const town=data?.town;const nextId=tour.townIds[tour.stopIndex+1];const next=data?.towns?.find((x:any)=>x.id===nextId);
 const travel=()=>next&&act(async()=>{const d=await api('/tours/'+tour.id+'/travel',{method:'POST',body:JSON.stringify({townId:next.id})});return d});
 const investigate=(kind:string)=>act(async()=>api('/tours/'+tour.id+'/investigations',{method:'POST',body:JSON.stringify({kind})}));
 const choosePlay=(id:string)=>setDraft((x:any)=>({...x,playId:id}));
 const addAction=(id:string)=>setDraft((x:any)=>({...x,timeline:[...x.timeline,{actionId:id,actorIds:[tour.actors[0].id],act:x.timeline.length%3,slot:x.timeline.length%4}]}));
 const saveProduction=()=>act(async()=>{const v=await api('/tours/'+tour.id+'/production/validate',{method:'POST',body:JSON.stringify(draft)});if(!v.valid)throw Error(v.errors.join('；'));return api('/tours/'+tour.id+'/production',{method:'PUT',body:JSON.stringify(draft)})});
 const perform=()=>act(async()=>api('/tours/'+tour.id+'/performances',{method:'POST',headers:{'Idempotency-Key':crypto.randomUUID()},body:JSON.stringify(draft)}));const rest=()=>act(async()=>api('/tours/'+tour.id+'/rest',{method:'POST'}));const finale=()=>act(async()=>api('/tours/'+tour.id+'/finale',{method:'POST'}));
 return <div className="app"><header><div className="brand">木偶剧团巡演</div><div className="stats"><b>第 {tour.stopIndex+1} 站</b><span>资金 {tour.funds}</span><span>声望 {tour.reputation}</span><span>灵感 {tour.inspiration}</span></div></header><main className="shell"><section className="hero"><div><small>{town?.region||'巡演路上'}</small><h1>{tour.status==='COMPLETED'?'巡演落幕':town?.name||'下一站'}</h1><p>{tour.status==='COMPLETED'?msg||'每一次提线，都会留下回声。':town?`${town.legend} · ${town.audience}`:'选择路线，去遇见新的传说。'}</p></div><div className="status">{tour.status.replaceAll('_',' ')}</div></section>{msg&&<div className="notice">{msg}</div>}
 {tour.status==='ROUTE_SELECTION'&&<section className="panel"><h2>选择下一站</h2><div className="route"><div className="town current"><strong>{town?.name||'起点'}</strong><small>当前剧场</small></div><div className="path">→</div><button className="town choice" onClick={travel} disabled={!next||busy}><strong>{next?.name||'路线已结束'}</strong><small>{next?`旅费 ${Math.max(12,Math.round(next.capacity/8))} · ${next.legend}`:'准备终场'}</small></button></div><button className="secondary" onClick={rest}>让全员休息，恢复 25 体力</button>{tour.stopIndex>=tour.townIds.length-1&&<button onClick={finale}>进入终局</button>}</section>}
 {tour.status==='INVESTIGATING'&&<section className="panel"><h2>在 {town.name} 了解传说</h2><p className="muted">调查会揭示结尾线索，排练则让动作更稳。</p><div className="choices"><button onClick={()=>investigate('market')}>逛市集<small>寻找观众口味</small></button><button onClick={()=>investigate('tavern')}>听酒馆故事<small>了解传说禁忌</small></button><button onClick={()=>investigate('shrine')}>拜访神龛<small>确认象征物</small></button><button onClick={()=>investigate('rehearse')}>后台排练<small>不揭示线索</small></button></div></section>}
 {(tour.status==='PREPARING'||tour.status==='READY')&&<section className="grid"><div className="panel"><h2>选一出戏</h2><div className="play-list">{(data?.plays||[]).map((p:any)=><button className={draft.playId===p.id?'selected':''} key={p.id} onClick={()=>choosePlay(p.id)}><b>{p.name}</b><small>{p.blurb}</small><em>{p.tags.join(' · ')}</em></button>)}</div></div><div className="panel"><h2>编排木偶动作</h2><p className="muted">点击动作加入时间轴，后端会检查演员体力和时间冲突。</p><div className="actions">{(data?.actions||[]).map((a:any)=><button key={a.id} onClick={()=>addAction(a.id)}>{a.name}<small>{a.duration} 拍 · {a.stamina} 体力</small></button>)}</div><div className="timeline">{draft.timeline.map((e:any,i:number)=><div key={i}><span>幕 {e.act+1} · 拍 {e.slot+1}</span><b>{data?.actions?.find((a:any)=>a.id===e.actionId)?.name}</b><small>{tour.actors.find((a:any)=>a.id===e.actorIds[0])?.name}</small></div>)}</div><h3>结尾改写</h3><div className="endings">{[0,1,2].map((slot)=><select key={slot} value={draft.endings[slot]} onChange={e=>setDraft((x:any)=>({...x,endings:x.endings.map((v:number,i:number)=>i===slot?Number(e.target.value):v)}))}>{(data?.plays?.find((p:any)=>p.id===draft.playId)?.endings||[]).map((x:string,i:number)=><option key={i} value={i}>{x}</option>)}</select>)}</div><button onClick={saveProduction} disabled={busy}>保存编排并检查</button>{tour.status==='READY'&&<button className="perform" onClick={perform} disabled={busy}>确认演出</button>}</div><aside className="panel"><h2>剧团状态</h2>{tour.actors.map((a:any)=><div className="actor" key={a.id}><div><b>{a.name}</b><small>{a.role} · Lv.{a.level}</small></div><meter min="0" max="100" value={a.stamina}/><small>体力 {a.stamina}</small></div>)}<button className="secondary" onClick={rest}>全员休息</button></aside></section>}
 {tour.status==='FINALE_READY'&&<section className="panel finale"><h2>终站的帷幕已经升起</h2><p>五座小镇的回声汇聚成最后一场演出。你的选择将决定剧团留下什么。</p><button onClick={finale} disabled={busy}>演出终局</button></section>}
 {perf&&<section className="panel result"><h2>演出结算</h2><div className="score">{perf.score}<small> / 100</small></div><p>{perf.feedback}</p><div className="ledger"><span>票房 <b>+{perf.income}</b></span><span>已记录为不可变演出快照</span></div></section>}
 {tour.status==='COMPLETED'&&<section className="panel"><h2>剧团档案</h2><p>本次巡演走过 {tour.visited.length} 座小镇，留下 {tour.history.length} 场演出记录。</p><button onClick={()=>{localStorage.removeItem('tour');location.reload()}}>开启新的巡演</button></section>}
 </main></div>}
createRoot(document.getElementById('root')!).render(<App/>);
