import express, { type Request, type Response } from 'express';
import cors from 'cors';
import { randomUUID } from 'node:crypto';
import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { actors, actions, plays, towns, type Actor } from './content.js';
import { canTransition, applyTransition, migrateTour, createSerializer, route, type Draft, type Tour } from './rules.js';

const file = join(process.cwd(), 'data.json');
const load=():Tour[]=>{if(!existsSync(file))return[];try{const raw=JSON.parse(readFileSync(file,'utf8'));return Array.isArray(raw)?raw.map(migrateTour).filter((t):t is Tour=>!!t):[]}catch{return[]}};
let tours:Tour[] = load();
let persistTimer:ReturnType<typeof setTimeout>|undefined; const persist=()=>{if(persistTimer)clearTimeout(persistTimer);persistTimer=setTimeout(()=>writeFileSync(file,JSON.stringify(tours,null,2)),120)};
const serialize=createSerializer();
const app=express(); app.use(cors()); app.use(express.json({limit:'1mb'}));
const ok=(res:any,data:any)=>res.json(data); const fail=(res:any,code:string,message:string,status=400)=>res.status(status).json({code,message});
const getTour=(req:Request,res:Response):Tour|null=>{const t=tours.find(x=>x.id===req.params.id);if(!t){fail(res,'TOUR_NOT_FOUND','存档不存在',404);return null}return t};
function town(t:Tour){return towns.find(x=>x.id===t.townIds[t.stopIndex])!}
// 所有改写存档的请求都经由此处：同一存档的并发写操作串行执行，且都在执行时重新校验同一份迁移规则
const mutate=(req:Request,res:Response,fn:(t:Tour)=>void)=>{const t=getTour(req,res);if(!t||!('id'in t))return;serialize(t.id,()=>fn(t)).catch(()=>{if(!res.headersSent)fail(res,'INTERNAL_ERROR','服务器开小差了，请稍后再试',500)})};
app.get('/health/live',(_,res)=>ok(res,{ok:true}));
app.get('/api/v1/content/bootstrap',(_,res)=>ok(res,{actors,actions,plays,towns}));
app.get('/api/v1/tours',(_,res)=>ok(res,{tours:tours.map(t=>({id:t.id,name:t.name,status:t.status,stopIndex:t.stopIndex,funds:t.funds,reputation:t.reputation}))}));
app.post('/api/v1/tours',(req,res)=>{const body=req.body??{};const name=String(body.name||'未命名剧团').trim().slice(0,24)||'未命名剧团';const seed=Number.isFinite(body.seed)?Number(body.seed):Math.floor(Math.random()*1000000); const t:Tour={id:randomUUID(),name,seed,status:'INVESTIGATING',townIds:route(seed),stopIndex:0,funds:420,reputation:50,inspiration:3,version:1,actors:actors.slice(0,3).map(a=>({...a,level:1,xp:0,stamina:a.stamina,fatigue:0})),visited:[],clues:{},history:[],unlocked:[]};tours.push(t);persist();ok(res,{tour:t})});
app.get('/api/v1/tours/:id',(req,res)=>{const t=getTour(req,res);if(!t||!('id'in t))return; ok(res,{tour:t,town:town(t),plays,actions,towns})});
app.post('/api/v1/tours/:id/travel',(req,res)=>mutate(req,res,t=>{if(!canTransition(t,'travel'))return fail(res,'INVALID_TOUR_STATE','当前阶段不能移动',409);const next=String(req.body?.townId||'');if(t.townIds[t.stopIndex+1]!==next)return fail(res,'INVALID_ROUTE','请选择相邻路线');const target=towns.find(x=>x.id===next)!;const cost=Math.max(12,Math.round(target.capacity/8));if(t.funds<cost)return fail(res,'INSUFFICIENT_RESOURCE','资金不足以抵达下一站',422);t.funds-=cost;t.stopIndex++;t.status=applyTransition(t,'travel');t.version++;persist();ok(res,{tour:t,town:target,cost})}));
app.post('/api/v1/tours/:id/investigations',(req,res)=>mutate(req,res,t=>{if(!canTransition(t,'investigate'))return fail(res,'INVALID_TOUR_STATE','当前阶段不能调查',409);const cur=town(t);const kind=String(req.body?.kind||'');if(!['market','tavern','shrine','rehearse'].includes(kind))return fail(res,'VALIDATION_ERROR','未知调查类型');t.clues[cur.id]=Array.from(new Set([...(t.clues[cur.id]||[]),...cur.clues.slice(0,kind==='rehearse'?0:kind==='market'?1:kind==='tavern'?2:3)]));t.status=applyTransition(t,'investigate');t.version++;persist();ok(res,{tour:t,clues:t.clues[cur.id]})}));
app.get('/api/v1/tours/:id/production',(req,res)=>{const t=getTour(req,res);if(!t||!('id'in t))return;ok(res,{draft:t.draft||{playId:plays[0].id,assignments:Object.fromEntries(t.actors.map(a=>[a.id,'main'])),timeline:[],endings:[0,0,0]},plays,actions,actors:t.actors})});
function validate(t:Tour,d:Partial<Draft>){const errors:string[]=[];if(!d||typeof d!=='object')return {errors:['编排数据格式错误'],p:undefined};const p=plays.find(x=>x.id===d.playId);if(!p)errors.push('剧目不存在');const timeline=Array.isArray(d.timeline)?d.timeline:[];if(timeline.length===0)errors.push('至少安排一个木偶动作');const seen=new Set<string>();for(const e of timeline){if(!e||typeof e!=='object'){errors.push('动作数据格式错误');continue}const a=actions.find(x=>x.id===e.actionId);if(!a)errors.push('包含未知动作');if(!Number.isInteger(e.slot)||!Number.isInteger(e.act)||e.slot<0||e.slot>3||e.act<0||e.act>2)errors.push('动作位置超出时间轴');const ids=Array.isArray(e.actorIds)?e.actorIds:[];if(ids.length===0)errors.push('每个动作至少需要一名演员');for(const id of ids){if(!t.actors.some(actor=>actor.id===id))errors.push('包含未知演员');const occupied=`${id}-${e.act}-${e.slot+((a?.duration||1)-1)}`;if(seen.has(occupied))errors.push('同一演员存在时间冲突');seen.add(occupied)}}for(const a of t.actors){const used=timeline.filter(e=>Array.isArray(e?.actorIds)&&e.actorIds.includes(a.id)).reduce((n,e)=>n+(actions.find(x=>x.id===e.actionId)?.stamina||0),0);if(used>a.stamina+10)errors.push(`${a.name}体力不足`) }const endings=Array.isArray(d.endings)?d.endings:[];if(endings.length!==3||endings.some(x=>!Number.isInteger(x)||x<0||x>2))errors.push('结局选择不完整');return {errors,p}};
app.post('/api/v1/tours/:id/production/validate',(req,res)=>{const t=getTour(req,res);if(!t||!('id'in t))return;const d=req.body as Draft;const r=validate(t,d);ok(res,{valid:r.errors.length===0,errors:r.errors,preview:{funds:Math.max(0,t.funds-8),inspiration:Math.max(0,t.inspiration-(Array.isArray(d?.endings)&&d.endings.length===3?1:0))}})});
app.put('/api/v1/tours/:id/production',(req,res)=>mutate(req,res,t=>{if(!canTransition(t,'saveProduction'))return fail(res,'INVALID_TOUR_STATE','当前阶段不能保存编排',409);const d=req.body as Draft;const r=validate(t,d);if(r.errors.length)return fail(res,'INVALID_PRODUCTION',r.errors.join('；'),422);t.draft=d;t.status=applyTransition(t,'saveProduction');t.version++;persist();ok(res,{tour:t})}));
app.post('/api/v1/tours/:id/performances',(req,res)=>mutate(req,res,t=>{const key=String(req.header('Idempotency-Key')||'');const previous=key&&t.history.find((x:any)=>x.idempotencyKey===key);if(previous){ok(res,{performance:previous,tour:t,replayed:true});return}if(!canTransition(t,'perform'))return fail(res,'INVALID_TOUR_STATE','请先完成合法编排',409);const submitted=req.body as Partial<Draft>|undefined;const d=submitted?.playId?submitted as Draft:t.draft!;const r=validate(t,d);if(r.errors.length)return fail(res,'INVALID_PRODUCTION',r.errors.join('；'),422);const p=r.p!,cur=town(t);const tagScore=d.timeline.reduce((s:number,e:any)=>s+(actions.find(a=>a.id===e.actionId)?.tags.some(x=>cur.mood.includes(x)||p.tags.includes(x))?5:1),0);const score=Math.max(0,Math.min(100,45+tagScore+Math.min(20,t.reputation/5)-d.timeline.length*1));const fill=Math.min(1,0.45+t.reputation/160+tagScore/250);const income=Math.round(cur.capacity*fill*cur.ticket/10);const feedback=score>=75?`${cur.audience}喜欢你对“${cur.legend}”的回应，散场后仍在讨论结尾。`:`观众希望动作更贴近${cur.mood}的气氛；有人记住了你的勇气。`;const perf={id:randomUUID(),idempotencyKey:key||undefined,townId:cur.id,score,income,feedback,ending:d.endings[2],snapshot:d,createdAt:new Date().toISOString()};t.history.push(perf);t.funds+=income;t.reputation=Math.max(0,Math.min(100,t.reputation+Math.round((score-55)/5)));t.inspiration=Math.max(0,t.inspiration+(score>72?1:0));for(const a of t.actors){a.xp+=Math.round(score/4);a.stamina=Math.max(10,a.stamina-12);a.fatigue=Math.min(3,a.fatigue+(score<50?1:0));if(a.xp>=a.level*100){a.level++;a.xp-=a.level*100}}t.visited.push(cur.id);t.status=applyTransition(t,'perform');t.draft=undefined;t.version++;persist();ok(res,{performance:perf,tour:t})}));
app.post('/api/v1/tours/:id/rest',(req,res)=>mutate(req,res,t=>{if(!canTransition(t,'rest'))return fail(res,'INVALID_TOUR_STATE','当前阶段不能休息',409);for(const a of t.actors)a.stamina=Math.min(100,a.stamina+25),a.fatigue=Math.max(0,a.fatigue-1);t.version++;persist();ok(res,{tour:t})}));
app.get('/api/v1/tours/:id/history',(req,res)=>{const t=getTour(req,res);if(!t||!('id'in t))return;ok(res,{history:t.history})});
app.post('/api/v1/tours/:id/finale',(req,res)=>mutate(req,res,t=>{if(!canTransition(t,'finale'))return fail(res,'INVALID_TOUR_STATE','终局尚未开放',409);const avg=t.history.slice(1).reduce((n,x)=>n+x.score,0)/Math.max(1,t.history.length-1);t.status=applyTransition(t,'finale');t.version++;persist();ok(res,{ending:avg>=75?'万镇喝彩':avg>=55?'忠于舞台':'散场之后',average:Math.round(avg),tour:t})}));
app.use(express.static(join(process.cwd(),'dist-web')));
app.listen(3001,()=>console.log('API listening on http://localhost:3001'));
